apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: my-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
      run: my-nginx
  template:
    metadata:
      labels:
        env: dev
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: jeonghyuck/jenkins-test:9
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: ssl-cert
          mountPath: /etc/ssl/certs
          subPath: tls.crt
        - name: ssl-cert
          mountPath: /etc/ssl/private
          subPath: tls.key
        - name: index-html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: ssl-cert
        secret:
          secretName: nginx-secret
      - name: index-html-volume
        configMap:
          name: nginx-index-html
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  namespace: my-nginx
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30100  # HTTP에 대한 NodePort (필요에 따라 조정)
      protocol: TCP
    - port: 443
      targetPort: 443
      nodePort: 30101  # HTTPS에 대한 NodePort
      protocol: TCP
  selector:
    env: dev
    run: my-nginx
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: backend1-service
  namespace: my-nginx
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: backend1
---
apiVersion: v1
kind: Service
metadata:
  name: backend2-service
  namespace: my-nginx
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: backend2

