apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: my-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
      run: my-nginx
  template:
    metadata:
      labels:
        env: dev
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: jeonghyuck/jenkins-test:9
        ports:
        - containerPort: 80
        volumeMounts:
        - name: index-html-volume
          mountPath: /usr/share/nginx/html/index.html  # Ensure it's mounted as index.html
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi
      volumes:
      - name: index-html-volume
        configMap:
          name: nginx-index-html  # The ConfigMap you created
