apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: my-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
      run: my-nginx
  template:
    metadata:
      labels:
        env: dev
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: jeonghyuck/jenkins-test:9
        ports:
        - containerPort: 80
        volumeMounts:
        - name: index-html-volume
          mountPath: /usr/share/nginx/html  # Mount ConfigMap to the HTML directory, not to a file
      volumes:
      - name: index-html-volume
        configMap:
          name: nginx-index-html  # Reference to your ConfigMap

---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  namespace: my-nginx
spec:
  ports:
    - port: 80           
      targetPort: 80      
      nodePort: 30100      
      protocol: TCP
  selector:
    env: dev
    run: my-nginx
  type: NodePort            
